name:                aoc2024
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - containers

executables:
  aoc2024:
    source-dirs:      src/
    main:             Main.hs
    build-target:     bin
